package javachatserverprogramui;

import java.awt.Color;
import java.util.Vector;
import java.net.*;
import java.io.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author edsel
 */
public class JSUI extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    private Vector<String> vsMsg;
    private String message;
    private ChatServer cs;
    
    public JSUI(ChatServer _cs) {
        vsMsg = new Vector<String>();
        initComponents();
        cs = _cs;
    }

     public JSUI() {
        vsMsg = new Vector<String>();
        initComponents();
        this.cs = null;
     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f_connect = new javax.swing.JFrame();
        lbld_server = new javax.swing.JLabel();
        lbld_port = new javax.swing.JLabel();
        tfd_port = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        f_Doc = new javax.swing.JFrame();
        sp_Doc = new javax.swing.JScrollPane();
        ta_Doc = new javax.swing.JTextArea();
        f_about = new javax.swing.JFrame();
        sp_about = new javax.swing.JScrollPane();
        ta_about = new javax.swing.JTextArea();
        tab_server = new javax.swing.JTabbedPane();
        sp_server = new javax.swing.JScrollPane();
        ta_server = new javax.swing.JTextArea();
        pnl_message = new javax.swing.JPanel();
        lbl_message = new javax.swing.JLabel();
        tf_msg = new javax.swing.JTextField();
        sp_client = new javax.swing.JScrollPane();
        list_client = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        
        jlabel_c = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        menu_main = new javax.swing.JMenu();
        mi_connect = new javax.swing.JMenuItem();
        mi_disconnect = new javax.swing.JMenuItem();
        mi_exit = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenu();
        mi_docs = new javax.swing.JMenuItem();
        mi_about = new javax.swing.JMenuItem();

        lbld_server.setText("Enter the port number for Server and Client Connection.");

        lbld_port.setText("Port:");

        tfd_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_portActionPerformed(evt);
            }
        });

        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout f_connectLayout = new javax.swing.GroupLayout(f_connect.getContentPane());
        f_connect.getContentPane().setLayout(f_connectLayout);
        f_connectLayout.setHorizontalGroup(
            f_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_connectLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(f_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(f_connectLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(f_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(f_connectLayout.createSequentialGroup()
                                .addComponent(btn_connect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cancel))
                            .addGroup(f_connectLayout.createSequentialGroup()
                                .addComponent(lbld_port)
                                .addGap(59, 59, 59)
                                .addComponent(tfd_port, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbld_server, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        f_connectLayout.setVerticalGroup(
            f_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f_connectLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lbld_server)
                .addGap(18, 18, 18)
                .addGroup(f_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbld_port)
                    .addComponent(tfd_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(f_connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_connect)
                    .addComponent(btn_cancel))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        ta_Doc.setColumns(20);
        ta_Doc.setRows(5);
        sp_Doc.setViewportView(ta_Doc);

        javax.swing.GroupLayout f_DocLayout = new javax.swing.GroupLayout(f_Doc.getContentPane());
        f_Doc.getContentPane().setLayout(f_DocLayout);
        f_DocLayout.setHorizontalGroup(
            f_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(f_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f_DocLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sp_Doc, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        f_DocLayout.setVerticalGroup(
            f_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(f_DocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f_DocLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sp_Doc, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        f_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_aboutMouseClicked(evt);
            }
        });

        ta_about.setColumns(20);
        ta_about.setRows(5);
        sp_about.setViewportView(ta_about);

        javax.swing.GroupLayout f_aboutLayout = new javax.swing.GroupLayout(f_about.getContentPane());
        f_about.getContentPane().setLayout(f_aboutLayout);
        f_aboutLayout.setHorizontalGroup(
            f_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(f_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f_aboutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sp_about, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        f_aboutLayout.setVerticalGroup(
            f_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(f_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f_aboutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sp_about, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta_server.setEditable(false);
        ta_server.setColumns(20);
        ta_server.setRows(5);
        ta_server.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ta_serverMouseClicked(evt);
            }
        });
        sp_server.setViewportView(ta_server);

        tab_server.addTab("Server Name", sp_server);

        lbl_message.setText("Commands / Message");

        tf_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_msgActionPerformed(evt);
            }
        });
        tf_msg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_msgKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_messageLayout = new javax.swing.GroupLayout(pnl_message);
        pnl_message.setLayout(pnl_messageLayout);
        pnl_messageLayout.setHorizontalGroup(
            pnl_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_messageLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tf_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnl_messageLayout.setVerticalGroup(
            pnl_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        list_client.setEnabled(false);
        sp_client.setViewportView(list_client);

        jlabel_c.setText("Clients");
        jScrollPane1.setViewportView(jlabel_c);

        menu_main.setText("Setup");
        menu_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_mainMouseClicked(evt);
            }
        });

        mi_connect.setText("Connect");
        mi_connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_connectMouseClicked(evt);
            }
        });
        mi_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_connectActionPerformed(evt);
            }
        });
        menu_main.add(mi_connect);

        mi_disconnect.setText("Disconnect");
        mi_disconnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_disconnectMouseClicked(evt);
            }
        });
        mi_disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_disconnectActionPerformed(evt);
            }
        });
        menu_main.add(mi_disconnect);

        mi_exit.setText("Exit");
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        menu_main.add(mi_exit);

        jMenuBar.add(menu_main);

        menu_help.setText("Help");

        mi_docs.setText("Docs");
        mi_docs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_docsMouseClicked(evt);
            }
        });
        mi_docs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_docsActionPerformed(evt);
            }
        });
        menu_help.add(mi_docs);

        mi_about.setText("About");
        mi_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_aboutActionPerformed(evt);
            }
        });
        menu_help.add(mi_about);

        jMenuBar.add(menu_help);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(pnl_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sp_client, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addComponent(tab_server, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab_server)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_client, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_msgActionPerformed
        // TODO add your handling code here:
            //this.ta_server.append(message + "\n");
            this.repaint();
            
    }//GEN-LAST:event_tf_msgActionPerformed

    private void mi_docsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_docsActionPerformed
        // TODO add your handling code here:
        f_Doc.setSize(400,400);
        ta_Doc.setSize(350, 350);
        sp_Doc.setSize(350, 350);
        f_Doc.setTitle("Documentation.");
        f_Doc.setDefaultCloseOperation(1);
        f_Doc.setVisible(true);
        f_Doc.show(true);
        ta_Doc.setText("Server Menu -> Connect -> Sets Port for the server and clients to talk in.\n"
                + "Server Menu -> Disconnect -> Closes the server and its ports as well as it disconnects the user.\n"
                + "Server Menu -> Exit -> Quits this program.\n");
        
        ta_Doc.append("\n");
        ta_Doc.append("Help Menu -> Docs -> Opens this help overview\n"
                + "Help Menu -> About -> Credits the author and contributor of this program.\n");
        f_Doc.repaint();
    }//GEN-LAST:event_mi_docsActionPerformed

    private void tf_msgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_msgKeyPressed
        // TODO add your handling code here:
            message = tf_msg.getText();
             if( evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER )
             {
                 cs.handle("Server: ", message);
             tf_msg.setText("");
             }
                     
    }//GEN-LAST:event_tf_msgKeyPressed

    private void mi_connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_connectMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mi_connectMouseClicked

    private void mi_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_connectActionPerformed
        // TODO add your handling code here:
        f_connect.setSize(400,400);
        
        f_connect.setTitle("Set port for Server and client Connection.");
        f_connect.setDefaultCloseOperation(1);
        f_connect.setVisible(true);
        f_connect.show(true);
        f_connect.repaint();
 
    }//GEN-LAST:event_mi_connectActionPerformed

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        // TODO add your handling code here:
        
        f_connect.setVisible(true);
        tab_server.setTitleAt(0, "Default Channel at port: " + tfd_port.getText() );
        cs = new ChatServer(Integer.parseInt(tfd_port.getText()), this);
        f_connect.setVisible(false);
        list_client.setModel(cs.model);
    }//GEN-LAST:event_btn_connectActionPerformed

    private void tfd_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_portActionPerformed

    private void menu_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mainMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menu_mainMouseClicked

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed
        // TODO add your handling code here:
        if(cs != null){
        for(int i=0; i < cs.clientCount; i++){
            try{
                cs.get_cht()[i].close();
            }catch (IOException ioe){
                System.out.print(ioe);
            }
        }
        cs.stop();
        }
        
        System.exit(0);
    }//GEN-LAST:event_mi_exitActionPerformed

    private void mi_disconnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_disconnectMouseClicked
        // TODO add your handling code here:
        for(int i=0; i < cs.clientCount; i++){
            try{
                cs.get_cht()[i].close();
            }catch (IOException ioe){
                System.out.print(ioe);
            }
        }
        cs.stop();
    }//GEN-LAST:event_mi_disconnectMouseClicked

    private void mi_docsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_docsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mi_docsMouseClicked

    private void ta_serverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_serverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ta_serverMouseClicked

    private void f_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_aboutMouseClicked
        // TODO add your handling code here:
        f_about.setSize(400,400);        

        f_about.setTitle("About the credits of this program.");        
        f_about.setDefaultCloseOperation(1);        
        f_about.setVisible(true);        
        f_about.show(true);        
        f_about.setTitle("Java Chat Program\n");        
        ta_about.setText("Java Chat Program\n"        
                + "Conceptualized, researched and developed by Edsel Malasig\n"        
                + "Resources where taken from tenouk.com\n"        
                + "as well as Carannos book\n"        
                + "and O'Reileys Network Programming for Java\n"        
                + "This software is licensed under GPL2\n"        
                + "It is free and opensource.");        
        f_about.repaint();        
        
        
    }//GEN-LAST:event_f_aboutMouseClicked

    private void mi_disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_disconnectActionPerformed
        // TODO add your handling code here:
        cs.disconnect();
    }//GEN-LAST:event_mi_disconnectActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void mi_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_aboutActionPerformed
        f_about.setSize(400,400);        
        
        f_about.setTitle("About the credits of this program.");        
        f_about.setDefaultCloseOperation(1);        
        f_about.setVisible(true);        
        f_about.show(true);        
        f_about.setTitle("Java Chat Program\n");        
        ta_about.setText("Java Chat Program\n"        
                + "Conceptualized, researched and developed by Edsel Malasig\n"        
                + "Resources where taken from tenouk.com\n"        
                + "as well as Carannos book\n"        
                + "and O'Reileys Network Programming for Java\n"        
                + "This software is licensed under GPL2\n"        
                + "It is free and opensource.");        
        f_about.repaint(); 
        
    }//GEN-LAST:event_mi_aboutActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /// Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_connect;
    private javax.swing.JFrame f_Doc;
    private javax.swing.JFrame f_about;
    private javax.swing.JFrame f_connect;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel_c;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbld_port;
    private javax.swing.JLabel lbld_server;
    private javax.swing.JList<String> list_client;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenu menu_main;
    private javax.swing.JMenuItem mi_about;
    private javax.swing.JMenuItem mi_connect;
    private javax.swing.JMenuItem mi_disconnect;
    private javax.swing.JMenuItem mi_docs;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JPanel pnl_message;
    private javax.swing.JScrollPane sp_Doc;
    private javax.swing.JScrollPane sp_about;
    private javax.swing.JScrollPane sp_client;
    private javax.swing.JScrollPane sp_server;
    private javax.swing.JTextArea ta_Doc;
    private javax.swing.JTextArea ta_about;
    private javax.swing.JTextArea ta_server;
    private javax.swing.JTabbedPane tab_server;
    private javax.swing.JTextField tf_msg;
    private javax.swing.JTextField tfd_port;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JTextArea get_ta_server(){
        return ta_server;
    }
    
    public javax.swing.JList<String> get_list_client(){
        return list_client;
    }
    
    public javax.swing.JTextField get_tf_msg(){
        return tf_msg;
    }
    
    public javax.swing.JTabbedPane get_tab_server(){
        return tab_server;
    }
    
    public String get_message(){
        return message;
    }
}
